### ISSUE TITLE
uasge for brats2020 augmentation

### ISSUE THREAD

**Issue by bhralz** [Au3C2/GVS#2]
Hi,
based on that I cant find any document for this repository, 
Is there any application of this code for augmentation of BRATS2020 in .nii?
if yes, how?
thanks

**Comment by Au3C2** [comment]
> Hi, based on that I cant find any document for this repository, Is there any application of this code for augmentation of BRATS2020 in .nii? if yes, how? thanks

Hi, 
thanks for your attention. We have a README file in the root path of this repo. if it's not clear, you can continue asking me for more detail.
the version of BRATS we used here is 2019, you can search on google for a download link. 

thanks again.
